# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0008_auto_20180612_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('briefTitle', models.CharField(max_length=64)),
                ('briefContent', models.CharField(max_length=1024)),
                ('briefReleaseTime', models.DateTimeField(auto_now=True)),
                ('briefType', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorQue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.CharField(max_length=4)),
                ('erroranswer', models.CharField(max_length=4)),
                ('count', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('testid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Questionitem')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=32)),
                ('uploadtime', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(blank=True, max_length=64, null=True)),
                ('path', models.CharField(max_length=128)),
                ('suffix', models.CharField(max_length=12, null=True)),
                ('visible', models.CharField(max_length=12, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Chapter')),
            ],
        ),
    ]
