# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-03 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isActive',
        ),
        migrations.AddField(
            model_name='user',
            name='lastlogin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
