# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-03 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chaptername', models.CharField(max_length=50)),
                ('chapterdescription', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='subchapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subchaptername', models.CharField(max_length=50)),
                ('chapterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.chapter')),
            ],
        ),
    ]
