# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-03 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_questionitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questionitem',
        ),
    ]
