# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-03 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_questionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapterdescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
