# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-07 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20180603_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionitem',
            name='chapterid',
        ),
    ]
