# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180603_0305'),
        ('student', '0007_remove_questionitem_chapterid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField()),
                ('questionlist', models.CharField(blank=True, max_length=1000, null=True)),
                ('answerlist', models.CharField(blank=True, max_length=1000, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='questionitem',
            name='visiable',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='questionitem',
            name='subchapterid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Subchapter'),
        ),
        migrations.AlterField(
            model_name='subchapter',
            name='chapterid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Chapter'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subchapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Subchapter'),
        ),
        migrations.AddField(
            model_name='grade',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
